networks:
  traefik.public:
    external: true

services:
  prod.formula:
    container_name: prod.formula
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped #change if you don't want your container restarting
    env_file:
      - ./env.prod
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.formula-prod.rule=Host(`formula.crf.mn`)"
      - "traefik.http.routers.formula-prod.entrypoints=websecure"
      - "traefik.http.routers.formula-prod.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.formula-prod.service=formula-service-prod"
      - "traefik.http.services.formula-service-prod.loadbalancer.server.port=3000"
    networks:
      - traefik.public