import "~/styles/globals.css";

import { Inter as FontSans } from "next/font/google";
import { cn } from "~/lib/util";
import { TooltipProvider } from "~/components/ui/tooltip";
import { ThemeProvider } from "~/components/provider/theme.provider";
import { ReactQueryClientProvider } from "~/components/provider/query.provider";
import { Suspense } from "react";
import PageLoader from "~/components/page-loader";

export const metadata = {
  title: "Formula Editor",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable,
      )}
      suppressHydrationWarning={true}
    >
      <body>
        <ReactQueryClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TooltipProvider>
              <Suspense fallback={<PageLoader />}>{children}</Suspense>
            </TooltipProvider>
          </ThemeProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
